#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _ANsyn_reg(void);
extern void _IA_reg(void);
extern void _Ih_reg(void);
extern void _Ihvip_reg(void);
extern void _Kaxon_reg(void);
extern void _Kdend_reg(void);
extern void _Ksoma_reg(void);
extern void _LcaMig_reg(void);
extern void _Naaxon_reg(void);
extern void _Nadend_reg(void);
extern void _Nasoma_reg(void);
extern void _STDPE2Syn_reg(void);
extern void _bgka_reg(void);
extern void _burststim2_reg(void);
extern void _cad_reg(void);
extern void _cadyn_reg(void);
extern void _cadyn_new_reg(void);
extern void _cagk_reg(void);
extern void _cal_reg(void);
extern void _calH_reg(void);
extern void _cancr_reg(void);
extern void _car_reg(void);
extern void _cat_reg(void);
extern void _ccanl_reg(void);
extern void _gskch_reg(void);
extern void _h_reg(void);
extern void _hNa_reg(void);
extern void _hha2_reg(void);
extern void _hha_old_reg(void);
extern void _iccr_reg(void);
extern void _ichan2_reg(void);
extern void _ichan2aa_reg(void);
extern void _ichan2bc_reg(void);
extern void _ichan2bs_reg(void);
extern void _ichan2vip_reg(void);
extern void _ikscr_reg(void);
extern void _kad_reg(void);
extern void _kadistcr_reg(void);
extern void _kap_reg(void);
extern void _kca_reg(void);
extern void _kdrcr_reg(void);
extern void _km_reg(void);
extern void _my_exp2syn_reg(void);
extern void _nafcr_reg(void);
extern void _nap_reg(void);
extern void _nca_reg(void);
extern void _nmda_reg(void);
extern void _regn_stim_reg(void);
extern void _somacar_reg(void);
extern void _vecstim_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," mechanisms//ANsyn.mod");
    fprintf(stderr," mechanisms//IA.mod");
    fprintf(stderr," mechanisms//Ih.mod");
    fprintf(stderr," mechanisms//Ihvip.mod");
    fprintf(stderr," mechanisms//Kaxon.mod");
    fprintf(stderr," mechanisms//Kdend.mod");
    fprintf(stderr," mechanisms//Ksoma.mod");
    fprintf(stderr," mechanisms//LcaMig.mod");
    fprintf(stderr," mechanisms//Naaxon.mod");
    fprintf(stderr," mechanisms//Nadend.mod");
    fprintf(stderr," mechanisms//Nasoma.mod");
    fprintf(stderr," mechanisms//STDPE2Syn.mod");
    fprintf(stderr," mechanisms//bgka.mod");
    fprintf(stderr," mechanisms//burststim2.mod");
    fprintf(stderr," mechanisms//cad.mod");
    fprintf(stderr," mechanisms//cadyn.mod");
    fprintf(stderr," mechanisms//cadyn_new.mod");
    fprintf(stderr," mechanisms//cagk.mod");
    fprintf(stderr," mechanisms//cal.mod");
    fprintf(stderr," mechanisms//calH.mod");
    fprintf(stderr," mechanisms//cancr.mod");
    fprintf(stderr," mechanisms//car.mod");
    fprintf(stderr," mechanisms//cat.mod");
    fprintf(stderr," mechanisms//ccanl.mod");
    fprintf(stderr," mechanisms//gskch.mod");
    fprintf(stderr," mechanisms//h.mod");
    fprintf(stderr," mechanisms//hNa.mod");
    fprintf(stderr," mechanisms//hha2.mod");
    fprintf(stderr," mechanisms//hha_old.mod");
    fprintf(stderr," mechanisms//iccr.mod");
    fprintf(stderr," mechanisms//ichan2.mod");
    fprintf(stderr," mechanisms//ichan2aa.mod");
    fprintf(stderr," mechanisms//ichan2bc.mod");
    fprintf(stderr," mechanisms//ichan2bs.mod");
    fprintf(stderr," mechanisms//ichan2vip.mod");
    fprintf(stderr," mechanisms//ikscr.mod");
    fprintf(stderr," mechanisms//kad.mod");
    fprintf(stderr," mechanisms//kadistcr.mod");
    fprintf(stderr," mechanisms//kap.mod");
    fprintf(stderr," mechanisms//kca.mod");
    fprintf(stderr," mechanisms//kdrcr.mod");
    fprintf(stderr," mechanisms//km.mod");
    fprintf(stderr," mechanisms//my_exp2syn.mod");
    fprintf(stderr," mechanisms//nafcr.mod");
    fprintf(stderr," mechanisms//nap.mod");
    fprintf(stderr," mechanisms//nca.mod");
    fprintf(stderr," mechanisms//nmda.mod");
    fprintf(stderr," mechanisms//regn_stim.mod");
    fprintf(stderr," mechanisms//somacar.mod");
    fprintf(stderr," mechanisms//vecstim.mod");
    fprintf(stderr, "\n");
  }
  _ANsyn_reg();
  _IA_reg();
  _Ih_reg();
  _Ihvip_reg();
  _Kaxon_reg();
  _Kdend_reg();
  _Ksoma_reg();
  _LcaMig_reg();
  _Naaxon_reg();
  _Nadend_reg();
  _Nasoma_reg();
  _STDPE2Syn_reg();
  _bgka_reg();
  _burststim2_reg();
  _cad_reg();
  _cadyn_reg();
  _cadyn_new_reg();
  _cagk_reg();
  _cal_reg();
  _calH_reg();
  _cancr_reg();
  _car_reg();
  _cat_reg();
  _ccanl_reg();
  _gskch_reg();
  _h_reg();
  _hNa_reg();
  _hha2_reg();
  _hha_old_reg();
  _iccr_reg();
  _ichan2_reg();
  _ichan2aa_reg();
  _ichan2bc_reg();
  _ichan2bs_reg();
  _ichan2vip_reg();
  _ikscr_reg();
  _kad_reg();
  _kadistcr_reg();
  _kap_reg();
  _kca_reg();
  _kdrcr_reg();
  _km_reg();
  _my_exp2syn_reg();
  _nafcr_reg();
  _nap_reg();
  _nca_reg();
  _nmda_reg();
  _regn_stim_reg();
  _somacar_reg();
  _vecstim_reg();
}
